### ISSUE TITLE
bowtie2 does not insert TABs into RG line

### ISSUE THREAD

**Issue by mmokrejs** [BenLangmead/bowtie2#274]
Hi,
  I am using bowtie 2.3.5.1 and try to get sample and other IDs recorded on the `@RG` line. Unfortunately, it seems bowtie2 does not write TABs as separators on the `@RG` line and also copies whole `@RG` line content onto every read line (instead of transferring just the `SM:` tag).

```
net.sf.samtools.SAMFormatException: Error parsing SAM header. @RG line missing SM tag. Line:
@RG	ID:H27CNAFXY.1.xBJ4303 PL:ILLUMINA LB:xBJ4303_ExomABC1_180709 PU:H27CNAFXY.1 SM:xBJ4303; File xBJ4303.adapterremoval.global.hg38.bam; Line number 3368
	at net.sf.samtools.SAMTextHeaderCodec.reportErrorParsingLine(SAMTextHeaderCodec.java:230)
	at net.sf.samtools.SAMTextHeaderCodec.access$100(SAMTextHeaderCodec.java:39)
	at net.sf.samtools.SAMTextHeaderCodec$ParsedHeaderLine.requireTag(SAMTextHeaderCodec.java:306)
	at net.sf.samtools.SAMTextHeaderCodec.parseRGLine(SAMTextHeaderCodec.java:160)
	at net.sf.samtools.SAMTextHeaderCodec.decode(SAMTextHeaderCodec.java:93)
	at net.sf.samtools.BAMFileReader.readHeader(BAMFileReader.java:393)
	at net.sf.samtools.BAMFileReader.<init>(BAMFileReader.java:146)
	at net.sf.samtools.BAMFileReader.<init>(BAMFileReader.java:114)
	at net.sf.samtools.SAMFileReader.init(SAMFileReader.java:514)
	at net.sf.samtools.SAMFileReader.<init>(SAMFileReader.java:167)
	at net.sf.samtools.SAMFileReader.<init>(SAMFileReader.java:122)
	at org.bioinfo.ngs.qc.qualimap.process.BamStatsAnalysis.run(BamStatsAnalysis.java:202)
	at org.bioinfo.ngs.qc.qualimap.main.BamQcTool.execute(BamQcTool.java:242)
	at org.bioinfo.ngs.qc.qualimap.main.NgsSmartTool.run(NgsSmartTool.java:190)
	at org.bioinfo.ngs.qc.qualimap.main.NgsSmartMain.main(NgsSmartMain.java:111)
```

I tried two appoaches ('\t' is really '\t', bwa expands it into TAB, bowtie2 should do the same IMO ideally also replace space if in input):

`bowtie2-align-s --rg-id "$flowcell"."$lane"."$sample" --rg "ID:$rgid\tPL:$platform\tLB:$rglb\tPU:$rgpu\tSM:$sample"`

`bowtie2-align-s --rg-id "$flowcell"."$lane"."$sample" --rg "ID:$rgid PL:$platform LB:$rglb PU:$rgpu SM:$sample"`

The latter yields (a bit edited to make it shorter):

```
@RG     ID:H27CNAFXY.1.xBJ4303 PL:ILLUMINA LB:xBJ4303_ExomABC1_180709 PU:H27CNAFXY.1 SM:xBJ4303
@PG     ID:bowtie2      PN:bowtie2      VN:2.3.5.1      CL:"bowtie2-align-s ... --rg-id H27CNAFXY.1.xBJ4303 --rg ID:H27CNAFXY.1.xBJ4303 PL:ILLUMINA LB:xBJ4303_ExomABC1_180709 PU:H27CNAFXY.1 SM:xBJ4303 --fr -x ftp.ncbi.nlm.nih.gov/1000genomes/ftp/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla -p 24 -q -1 xBJ4303.adapterremoval_R1.fastq.gz -2 xBJ4303.adapterremoval_R2.fastq.gz"
NS500595:187:H27CNAFXY:1:11101:23806:1063       83      chr17   79835303        42      80M     =       79835176        -207    CCCCTGCGCGCCCAAATCCAGCTTGGCACGGTTGTCAGTGGAGGAGTCCTGGAGGCCGGTCAGGACATTGGAACGACGGG        EEEEEEEEEEEEEEEAEEEEEE/EEEEEEEE/EE/EEEEEEEEEEEEEEEEEEEEEEEE/EEEEEEEEEEEEEEEAAAAA        AS:i:0  XN:i:
0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  MD:Z:80 YS:i:-1 YT:Z:CP RG:Z:H27CNAFXY.1.xBJ4303 PL:ILLUMINA LB:xBJ4303_ExomABC1_180709 PU:H27CNAFXY.1 SM:xBJ4303
```

**Comment by mmokrejs** [comment]
What helps to fix the `@RG` line is to use [CTRL+V TAB] instead of writing `\t`.

`bowtie2-align-s --rg-id "$flowcell"."$lane"."$sample" --rg "ID:$rgid[CTRL+V TAB]PL:$platform[CTRL+V TAB]LB:$rglb[CTRL+V TAB]PU:$rgpu[CTRL+V TAB]SM:$sample"`

But, on alignment lines there are still `RG:Z:H27CNAFXY.1.xBJ4303 PL:ILLUMINA LB:xBJ4303_ExomABC1_180709 PU:H27CNAFXY.1 SM:xBJ4303` chunks repeated and just taking up space.

**Comment by mmokrejs** [comment]
A workaround is to replace the TAB on alignment lines with a space.:

`cat $mysam | sed -e 's/RG:Z:H27CNAFXY.1.xBJ4303]CTRL+V TAB]SM:xBJ4303/RG:Z:H27CNAFXY.1.xBJ4303 SM:xBJ4303/' | bamsort ..`

**Comment by ch4rr0** [comment]
Try this:
`bowtie2-align-s --rg-id "$flowcell"."$lane"."$sample" --rg "ID:$rgid" --rg "PL:$platform" --rg "LB:$rglb" --rg "PU:$rgpu" --rg "SM:$sample"`

**Comment by mmokrejs** [comment]
> A workaround is to replace the TAB on alignment lines with a space and drop the unnecessary fields:
> 
> `sed -e 's/RG:Z:H27CNAFXY.1.xBJ4303[CTRL+V TAB]PL:ILLUMINA[CTRL+V TAB]LB:xBJ4303_ExomABC1_180709[CTRL+V TAB]PU:H27CNAFXY.1[CTRL+V TAB]SM:xBJ4303/RG:Z:H27CNAFXY.1.xBJ4303 SM:xBJ4303/`

But the space inside `RG:Z:H27CNAFXY.1.xBJ4303 SM:xBJ4303` then causes `gatk-3.8-1-0-gf15c1c3ef` to break on the read alignment line as it thinks the `SM:xBJ4303` portion belongs to the readgroup (uses TAB as delimited). The error is:

```
##### ERROR MESSAGE: SAM/BAM/CRAM file htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter@5d4bf033 is malformed. Please see https://software.broadinstitute.org/gatk/documentation/article?id=1317for more information. Error details: Read NS500595:187:H27CNAFXY:3:11611:7134:1688 uses a read group (H27CNAFXY.1.xBJ4303 SM:xBJ4303) that is not defined in the BAM header, which is not valid.  Please see https://software.broadinstitute.org/gatk/documentation/article?id=59
```

So probaby after bamsort is fixed I could revert back to the `TAB` as separator on all alignment lines, and I could proceed with `gatk`. ... just kidding, will decompress the `BAM` and use `sed` to reintroduce the `TAB` in the already sorted stream, and re-create `BAM` file with its index. Or should I better drop the `SM:xBJ4303` altogether from alignment lines?

**Comment by mmokrejs** [comment]
> Try this:
> `bowtie2-align-s --rg-id "$flowcell"."$lane"."$sample" --rg "ID:$rgid" --rg "PL:$platform" --rg "LB:$rglb" --rg "PU:$rgpu" --rg "SM:$sample"`

Right, this ensures `TABs` are used in the `@RG` header line and also, just the `RG:Z:H27CNAFXY.1.xBJ4303` is included on every alignment line. The `SM/PL/LB/PU` individual components are not included on alignment lines.

Not sure what specs allow on alignment lines (see my previous comment).

**Comment by ch4rr0** [comment]
From the spec:
> RG:Z:readgroup The read group to which the read belongs. If @RG headers are present, then readgroup must match the RG-ID field of one of the headers.

https://samtools.github.io/hts-specs/SAMtags.pdf

**Comment by mmokrejs** [comment]
More importantly, the specs incidentally say

`SM    i       Template-independent mapping quality`

so from that I infer the `SM:xBJ4303` my values should not appear on the alignment lines, no matter if separated by a space or TAB. The `SZ:` tag exists incidentally but of a different purpose than `sample name`.
